server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: relia

app:
  monthly-closing:
    cron: "0 * * * * *"
    zone: "Asia/Seoul"

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET_KEY}
  accessExpiredMs: ${JWT_ACCESS_EXPIRED_MS}
  refreshExpiredMs: ${JWT_REFRESH_EXPIRED_MS}
