server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: relia

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET_KEY}
  accessExpiredMs: ${JWT_ACCESS_EXPIRED_MS}
  refreshExpiredMs: ${JWT_REFRESH_EXPIRED_MS}