CREATE TABLE organizations (
                               id CHAR(36) NOT NULL,
                               organization_code VARCHAR(50) NOT NULL,
                               parent_organization_id CHAR(36) NULL,
                               organization_name VARCHAR(100) NOT NULL,
                               organization_type VARCHAR(30) NOT NULL,
                               organization_address VARCHAR(255) NOT NULL,
                               organization_phone VARCHAR(30) NOT NULL,
                               organization_status VARCHAR(30) NOT NULL,
                               created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               created_by CHAR(36) NOT NULL,
                               updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                               updated_by CHAR(36) NOT NULL,
                               deleted_at DATETIME NULL,
                               deleted_by CHAR(36) NULL,
                               PRIMARY KEY (id),
                               UNIQUE KEY uk_organizations_code (organization_code),
                               CONSTRAINT chk_organizations_type CHECK (organization_type IN ('HQ', 'BRANCH')),
                               CONSTRAINT chk_organizations_status CHECK (organization_status IN ('ACTIVE', 'INACTIVE')),
                               CONSTRAINT fk_organizations_parent FOREIGN KEY (parent_organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE users (
                       id CHAR(36) NOT NULL,
                       emp_code VARCHAR(50) NOT NULL,
                       login_id VARCHAR(100) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       user_name VARCHAR(50) NOT NULL,
                       user_role VARCHAR(30) NOT NULL,
                       organization_id CHAR(36) NOT NULL,
                       user_status VARCHAR(30) NOT NULL,
                       phone VARCHAR(30) NULL,
                       email VARCHAR(100) NULL,
                       joined_at DATE NULL,
                       resigned_at DATE NULL,
                       last_login_at DATETIME NULL,
                       created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       created_by CHAR(36) NOT NULL,
                       updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                       updated_by CHAR(36) NOT NULL,
                       deleted_at DATETIME NULL,
                       deleted_by CHAR(36) NULL,
                       PRIMARY KEY (id),
                       UNIQUE KEY uk_users_emp_code (emp_code),
                       UNIQUE KEY uk_users_login_id (login_id),
                       CONSTRAINT chk_users_role CHECK (user_role IN ('FP', 'BRANCH_MANAGER', 'HQ_MANAGER', 'SYSTEM_ADMIN')),
                       CONSTRAINT chk_users_status CHECK (user_status IN ('ACTIVE', 'RESIGNED')),
                       CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE fp_monthly_info (
                                 id CHAR(36) NOT NULL,
                                 closing_month VARCHAR(7) NOT NULL,
                                 emp_code VARCHAR(50) NOT NULL,
                                 fp_name VARCHAR(50) NOT NULL,
                                 organization_code VARCHAR(50) NOT NULL,
                                 organization_name VARCHAR(100) NOT NULL,
                                 organization_type VARCHAR(30) NOT NULL,
                                 career_years INT NOT NULL,
                                 specialty_category VARCHAR(100) NOT NULL,
                                 preferred_customer_age INT NULL,
                                 preferred_customer_asset_level VARCHAR(30) NULL,
                                 consultation_channel VARCHAR(20) NOT NULL,
                                 current_contract_count INT NOT NULL,
                                 retention_rate DECIMAL(5,2) NOT NULL,
                                 consultation_count INT NOT NULL,
                                 handover_success_count INT NOT NULL,
                                 long_term_maintenance_rate DECIMAL(5,2) NOT NULL,
                                 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 created_by CHAR(36) NOT NULL,
                                 PRIMARY KEY (id),
                                 UNIQUE KEY uk_fp_monthly_info_month_emp (closing_month, emp_code),
                                 CONSTRAINT chk_fp_monthly_info_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$')
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE insurance_companies (
                                     id CHAR(36) NOT NULL,
                                     insurance_company_code VARCHAR(50) NOT NULL,
                                     insurance_company_name VARCHAR(100) NOT NULL,
                                     insurance_company_status VARCHAR(30) NOT NULL,
                                     insurance_company_phone VARCHAR(30) NOT NULL,
                                     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     created_by CHAR(36) NOT NULL,
                                     updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                     updated_by CHAR(36) NOT NULL,
                                     deleted_at DATETIME NULL,
                                     deleted_by CHAR(36) NULL,
                                     PRIMARY KEY (id),
                                     UNIQUE KEY uk_insurance_companies_code (insurance_company_code),
                                     CONSTRAINT chk_insurance_companies_status CHECK (insurance_company_status IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE insurance_categories (
                                      id CHAR(36) NOT NULL,
                                      insurance_category_code VARCHAR(50) NOT NULL,
                                      insurance_category_name VARCHAR(100) NOT NULL,
                                      insurance_category_status VARCHAR(30) NOT NULL,
                                      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      created_by CHAR(36) NOT NULL,
                                      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                      updated_by CHAR(36) NOT NULL,
                                      deleted_at DATETIME NULL,
                                      deleted_by CHAR(36) NULL,
                                      PRIMARY KEY (id),
                                      UNIQUE KEY uk_insurance_categories_code (insurance_category_code),
                                      CONSTRAINT chk_insurance_categories_status CHECK (insurance_category_status IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE insurance_products (
                                    id CHAR(36) NOT NULL,
                                    insurance_product_code VARCHAR(50) NOT NULL,
                                    insurance_company_id CHAR(36) NOT NULL,
                                    insurance_category_id CHAR(36) NOT NULL,
                                    insurance_product_name VARCHAR(200) NOT NULL,
                                    insurance_product_status VARCHAR(30) NOT NULL,
                                    insurance_start_date DATE NOT NULL,
                                    insurance_end_date DATE NULL,
                                    coverage_period_type VARCHAR(30) NOT NULL,
                                    coverage_period_years INT NULL,
                                    coverage_age_limit INT NULL,
                                    is_lifetime_coverage BOOLEAN NOT NULL,
                                    is_renewable BOOLEAN NOT NULL,
                                    renewal_cycle INT NULL,
                                    product_description TEXT NULL,
                                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    created_by CHAR(36) NOT NULL,
                                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                    updated_by CHAR(36) NOT NULL,
                                    deleted_at DATETIME NULL,
                                    deleted_by CHAR(36) NULL,
                                    PRIMARY KEY (id),
                                    UNIQUE KEY uk_insurance_products_code (insurance_product_code),
                                    CONSTRAINT chk_insurance_products_status CHECK (insurance_product_status IN ('ACTIVE', 'INACTIVE')),
                                    CONSTRAINT chk_insurance_products_coverage_period_type CHECK (coverage_period_type IN ('YEARS', 'AGE', 'LIFETIME')),
                                    CONSTRAINT fk_insurance_products_company FOREIGN KEY (insurance_company_id) REFERENCES insurance_companies(id),
                                    CONSTRAINT fk_insurance_products_category FOREIGN KEY (insurance_category_id) REFERENCES insurance_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE hr_monthly_closing (
                                    id CHAR(36) NOT NULL,
                                    closing_month VARCHAR(7) NOT NULL,
                                    user_id CHAR(36) NOT NULL,
                                    emp_code VARCHAR(50) NOT NULL,
                                    user_name VARCHAR(50) NOT NULL,
                                    user_role VARCHAR(30) NOT NULL,
                                    user_status VARCHAR(30) NOT NULL,
                                    organization_id CHAR(36) NOT NULL,
                                    closed_at DATETIME NOT NULL,
                                    PRIMARY KEY (id),
                                    UNIQUE KEY uk_hr_monthly_closing_month_user (closing_month, user_id),
                                    CONSTRAINT chk_hr_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_hr_monthly_closing_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_hr_monthly_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE organization_monthly_closing (
                                              id CHAR(36) NOT NULL,
                                              closing_month VARCHAR(7) NOT NULL,
                                              organization_id CHAR(36) NOT NULL,
                                              organization_code VARCHAR(50) NOT NULL,
                                              organization_name VARCHAR(100) NOT NULL,
                                              organization_type VARCHAR(30) NOT NULL,
                                              organization_status VARCHAR(30) NOT NULL,
                                              closed_at DATETIME NOT NULL,
                                              PRIMARY KEY (id),
                                              UNIQUE KEY uk_organization_monthly_closing_month_org (closing_month, organization_id),
                                              CONSTRAINT chk_organization_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_organization_monthly_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE customers (
                           id CHAR(36) NOT NULL,
                           customer_code VARCHAR(50) NOT NULL,
                           customer_fp_id CHAR(36) NOT NULL,
                           customer_status VARCHAR(30) NOT NULL,
                           customer_grade VARCHAR(30) NOT NULL,
                           interest_yn BOOLEAN NOT NULL,
                           interest_reason VARCHAR(30) NULL,
                           customer_name VARCHAR(50) NOT NULL,
                           customer_gender VARCHAR(10) NOT NULL,
                           customer_birth_date DATE NOT NULL,
                           customer_phone VARCHAR(30) NOT NULL,
                           customer_email VARCHAR(100) NOT NULL,
                           customer_zipcode VARCHAR(10) NOT NULL,
                           customer_address_road VARCHAR(255) NOT NULL,
                           customer_address_detail VARCHAR(255) NULL,
                           customer_job VARCHAR(100) NOT NULL,
                           customer_company_name VARCHAR(100) NOT NULL,
                           customer_annual_income DECIMAL(15,2) NOT NULL,
                           customer_asset_size DECIMAL(15,2) NOT NULL,
                           customer_debt_status VARCHAR(255) NOT NULL,
                           customer_is_smoker BOOLEAN NOT NULL,
                           customer_is_drinker BOOLEAN NOT NULL,
                           customer_marital_status VARCHAR(20) NOT NULL,
                           customer_dependents_count INT NOT NULL,
                           created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           created_by CHAR(36) NOT NULL,
                           updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                           updated_by CHAR(36) NOT NULL,
                           deleted_at DATETIME NULL,
                           deleted_by CHAR(36) NULL,
                           PRIMARY KEY (id),
                           UNIQUE KEY uk_customers_code (customer_code),
                           UNIQUE KEY uk_customers_phone (customer_phone),
                           CONSTRAINT chk_customers_status CHECK (customer_status IN ('PROSPECT', 'CONTRACTED', 'COMPLETED', 'TERMINATED')),
                           CONSTRAINT chk_customers_grade CHECK (customer_grade IN ('GENERAL', 'GOLD', 'VIP')),
                           CONSTRAINT chk_customers_interest_reason CHECK (interest_reason IS NULL OR interest_reason IN ('UNPAID', 'RENEWAL_DUE', 'MATURITY_DUE')),
                           CONSTRAINT fk_customers_fp FOREIGN KEY (customer_fp_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE SEQUENCE customer_code_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1;
CREATE TABLE disease_codes (
                               id CHAR(36) NOT NULL,
                               disease_code VARCHAR(50) NOT NULL,
                               disease_name VARCHAR(100) NOT NULL,
                               disease_category VARCHAR(50) NULL,
                               insurance_notice_required_yn BOOLEAN NOT NULL,
                               created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               created_by CHAR(36) NOT NULL,
                               updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                               updated_by CHAR(36) NOT NULL,
                               deleted_at DATETIME NULL,
                               deleted_by CHAR(36) NULL,
                               PRIMARY KEY (id),
                               UNIQUE KEY uk_disease_codes_code (disease_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE customer_underlying_diseases (
                                              id CHAR(36) NOT NULL,
                                              customer_id CHAR(36) NOT NULL,
                                              disease_code VARCHAR(50) NOT NULL,
                                              created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                              created_by CHAR(36) NOT NULL,
                                              updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                              updated_by CHAR(36) NOT NULL,
                                              deleted_at DATETIME NULL,
                                              deleted_by CHAR(36) NULL,
                                              PRIMARY KEY (id),
                                              UNIQUE KEY uk_customer_underlying_diseases_customer_disease (customer_id, disease_code),
                                              CONSTRAINT fk_customer_underlying_diseases_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
                                              CONSTRAINT fk_customer_underlying_diseases_disease_code FOREIGN KEY (disease_code) REFERENCES disease_codes(disease_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE contracts (
                           id CHAR(36) NOT NULL,
                           contract_code VARCHAR(50) NOT NULL,
                           customer_id CHAR(36) NOT NULL,
                           fp_id CHAR(36) NOT NULL,
                           insurance_product_id CHAR(36) NOT NULL,
                           contract_date DATE NOT NULL,
                           contract_start_date DATE NOT NULL,
                           contract_end_date DATE NOT NULL,
                           contract_status VARCHAR(30) NOT NULL,
                           payment_period_years INT NOT NULL,
                           payment_cycle VARCHAR(20) NOT NULL,
                           monthly_premium DECIMAL(15,2) NOT NULL,
                           coverage_start_date DATE NOT NULL,
                           coverage_end_date DATE NOT NULL,
                           coverage_summary TEXT NULL,
                           created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           created_by CHAR(36) NOT NULL,
                           updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                           updated_by CHAR(36) NOT NULL,
                           deleted_at DATETIME NULL,
                           deleted_by CHAR(36) NULL,
                           PRIMARY KEY (id),
                           UNIQUE KEY uk_contracts_code (contract_code),
                           CONSTRAINT chk_contracts_status CHECK (contract_status IN ('MAINTENANCE', 'LAPSED', 'TERMINATED', 'COMPLETED')),
                           CONSTRAINT fk_contracts_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
                           CONSTRAINT fk_contracts_fp FOREIGN KEY (fp_id) REFERENCES users(id),
                           CONSTRAINT fk_contracts_product FOREIGN KEY (insurance_product_id) REFERENCES insurance_products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE contract_monthly_closing (
                                          id CHAR(36) NOT NULL,
                                          closing_month VARCHAR(7) NOT NULL,
                                          contract_id CHAR(36) NOT NULL,
                                          contract_status VARCHAR(30) NOT NULL,
                                          payment_status VARCHAR(30) NOT NULL,
                                          current_payment_round INT NULL,
                                          maintenance_round INT NULL,
                                          lapse_yn BOOLEAN NOT NULL,
                                          lapse_at DATE NULL,
                                          terminated_yn BOOLEAN NOT NULL,
                                          terminated_at DATE NULL,
                                          customer_id CHAR(36) NOT NULL,
                                          fp_id CHAR(36) NOT NULL,
                                          contract_date DATE NOT NULL,
                                          contract_start_date DATE NOT NULL,
                                          contract_end_date DATE NOT NULL,
                                          payment_period_years INT NOT NULL,
                                          payment_cycle VARCHAR(20) NOT NULL,
                                          monthly_premium DECIMAL(15,2) NOT NULL,
                                          coverage_start_date DATE NOT NULL,
                                          coverage_end_date DATE NOT NULL,
                                          coverage_summary TEXT NULL,
                                          closed_at DATETIME NOT NULL,
                                          PRIMARY KEY (id),
                                          UNIQUE KEY uk_contract_monthly_closing_month_contract (closing_month, contract_id),
                                          CONSTRAINT chk_contract_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_contract_monthly_closing_contract_status CHECK (contract_status IN ('MAINTENANCE', 'LAPSED', 'TERMINATED', 'COMPLETED')),
    CONSTRAINT chk_contract_monthly_closing_payment_status CHECK (payment_status IN ('PAID', 'UNPAID')),
    CONSTRAINT fk_contract_monthly_closing_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_contract_monthly_closing_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_contract_monthly_closing_fp FOREIGN KEY (fp_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultations (
                               id CHAR(36) NOT NULL,
                               consultation_sequence INT NOT NULL,
                               customer_id CHAR(36) NOT NULL,
                               fp_id CHAR(36) NOT NULL,
                               contract_id CHAR(36) NULL,
                               consultation_type VARCHAR(30) NOT NULL,
                               consultation_channel VARCHAR(30) NOT NULL,
                               consulted_at DATETIME NOT NULL,
                               special_note TEXT NULL,
                               next_scheduled_at DATETIME NULL,
                               created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               created_by CHAR(36) NOT NULL,
                               updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                               updated_by CHAR(36) NOT NULL,
                               deleted_at DATETIME NULL,
                               deleted_by CHAR(36) NULL,
                               PRIMARY KEY (id),
                               CONSTRAINT chk_consultations_type CHECK (consultation_type IN ('NEW_CONTRACT', 'CLAIM', 'TERMINATION', 'RENEWAL')),
                               CONSTRAINT chk_consultations_channel CHECK (consultation_channel IN ('VISIT', 'PHONE', 'MESSAGE')),
                               CONSTRAINT fk_consultations_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
                               CONSTRAINT fk_consultations_fp FOREIGN KEY (fp_id) REFERENCES users(id),
                               CONSTRAINT fk_consultations_contract FOREIGN KEY (contract_id) REFERENCES contracts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_new_details (
                                          id CHAR(36) NOT NULL,
                                          consultation_id CHAR(36) NOT NULL,
                                          monthly_income DECIMAL(15,2) NULL,
                                          has_existing_insurance BOOLEAN NOT NULL,
                                          monthly_insurance_premium DECIMAL(15,2) NULL,
                                          existing_insurance_note VARCHAR(500) NULL,
                                          insurance_priority VARCHAR(100) NULL,
                                          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          created_by CHAR(36) NOT NULL,
                                          updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          updated_by CHAR(36) NOT NULL,
                                          deleted_at DATETIME NULL,
                                          deleted_by CHAR(36) NULL,
                                          PRIMARY KEY (id),
                                          UNIQUE KEY uk_consultation_new_details_consultation (consultation_id),
                                          CONSTRAINT fk_consultation_new_details_consultation FOREIGN KEY (consultation_id) REFERENCES consultations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_new_coverage_needs (
                                                 id CHAR(36) NOT NULL,
                                                 consultation_new_detail_id CHAR(36) NOT NULL,
                                                 coverage_type VARCHAR(50) NOT NULL,
                                                 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                 created_by CHAR(36) NOT NULL,
                                                 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                 updated_by CHAR(36) NOT NULL,
                                                 deleted_at DATETIME NULL,
                                                 deleted_by CHAR(36) NULL,
                                                 PRIMARY KEY (id),
                                                 UNIQUE KEY uk_consultation_new_coverage_needs_detail_type (consultation_new_detail_id, coverage_type),
                                                 CONSTRAINT chk_consultation_new_coverage_needs_type CHECK (coverage_type IN ('CANCER', 'HEART', 'LIFE', 'DEATH', 'LONG_TERM_CARE')),
                                                 CONSTRAINT fk_consultation_new_coverage_needs_detail FOREIGN KEY (consultation_new_detail_id) REFERENCES consultation_new_details(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_new_proposed_products (
                                                    id CHAR(36) NOT NULL,
                                                    consultation_new_detail_id CHAR(36) NOT NULL,
                                                    insurance_product_id CHAR(36) NOT NULL,
                                                    insurance_product_name VARCHAR(200) NOT NULL,
                                                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                    created_by CHAR(36) NOT NULL,
                                                    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                    updated_by CHAR(36) NOT NULL,
                                                    deleted_at DATETIME NULL,
                                                    deleted_by CHAR(36) NULL,
                                                    PRIMARY KEY (id),
                                                    UNIQUE KEY uk_consultation_new_proposed_products_detail_product (consultation_new_detail_id, insurance_product_id),
                                                    CONSTRAINT fk_consultation_new_proposed_products_detail FOREIGN KEY (consultation_new_detail_id) REFERENCES consultation_new_details(id),
                                                    CONSTRAINT fk_consultation_new_proposed_products_product FOREIGN KEY (insurance_product_id) REFERENCES insurance_products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_cancel_details (
                                             id CHAR(36) NOT NULL,
                                             consultation_id CHAR(36) NOT NULL,
                                             premium_burden BOOLEAN NOT NULL,
                                             renewal_premium_burden BOOLEAN NOT NULL,
                                             payment_difficulty BOOLEAN NOT NULL,
                                             coverage_dissatisfaction BOOLEAN NOT NULL,
                                             duplicate_insurance BOOLEAN NOT NULL,
                                             product_remodeling_review BOOLEAN NOT NULL,
                                             comparing_other_company BOOLEAN NOT NULL,
                                             moving_to_other_company BOOLEAN NOT NULL,
                                             planner_contact_dissatisfaction BOOLEAN NOT NULL,
                                             management_dissatisfaction BOOLEAN NOT NULL,
                                             retention_possibility VARCHAR(30) NOT NULL,
                                             created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             created_by CHAR(36) NOT NULL,
                                             updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             updated_by CHAR(36) NOT NULL,
                                             deleted_at DATETIME NULL,
                                             deleted_by CHAR(36) NULL,
                                             PRIMARY KEY (id),
                                             UNIQUE KEY uk_consultation_cancel_details_consultation (consultation_id),
                                             CONSTRAINT chk_consultation_cancel_details_retention CHECK (retention_possibility IN ('HIGH', 'MEDIUM', 'LOW')),
                                             CONSTRAINT fk_consultation_cancel_details_consultation FOREIGN KEY (consultation_id) REFERENCES consultations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_renewal_details (
                                              id CHAR(36) NOT NULL,
                                              consultation_id CHAR(36) NOT NULL,
                                              renewal_reason VARCHAR(50) NOT NULL,
                                              renewal_scheduled_date DATE NOT NULL,
                                              current_premium DECIMAL(15,2) NOT NULL,
                                              renewal_premium DECIMAL(15,2) NOT NULL,
                                              premium_change_rate DECIMAL(5,2) NOT NULL,
                                              coverage_change_type VARCHAR(30) NOT NULL,
                                              coverage_change_detail VARCHAR(500) NULL,
                                              customer_reaction VARCHAR(30) NOT NULL,
                                              consultation_result VARCHAR(30) NOT NULL,
                                              created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                              created_by CHAR(36) NOT NULL,
                                              updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                              updated_by CHAR(36) NOT NULL,
                                              deleted_at DATETIME NULL,
                                              deleted_by CHAR(36) NULL,
                                              PRIMARY KEY (id),
                                              UNIQUE KEY uk_consultation_renewal_details_consultation (consultation_id),
                                              CONSTRAINT fk_consultation_renewal_details_consultation FOREIGN KEY (consultation_id) REFERENCES consultations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_renewal_premium_change_reasons (
                                                             id CHAR(36) NOT NULL,
                                                             consultation_renewal_detail_id CHAR(36) NOT NULL,
                                                             reason_type VARCHAR(50) NOT NULL,
                                                             other_reason VARCHAR(50) NULL,
                                                             created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                             created_by CHAR(36) NOT NULL,
                                                             updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                             updated_by CHAR(36) NOT NULL,
                                                             deleted_at DATETIME NULL,
                                                             deleted_by CHAR(36) NULL,
                                                             PRIMARY KEY (id),
                                                             UNIQUE KEY uk_consultation_renewal_premium_change_reasons_detail_type (consultation_renewal_detail_id, reason_type),
                                                             CONSTRAINT chk_consultation_renewal_premium_change_reasons_type CHECK (reason_type IN ('AGE_INCREASE', 'RISK_CHANGE', 'LOSS_RATIO_CHANGE', 'COVERAGE_CHANGE', 'OTHER')),
                                                             CONSTRAINT fk_consultation_renewal_premium_change_reasons_detail FOREIGN KEY (consultation_renewal_detail_id) REFERENCES consultation_renewal_details(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_renewal_interests (
                                                id CHAR(36) NOT NULL,
                                                consultation_renewal_detail_id CHAR(36) NOT NULL,
                                                interest_type VARCHAR(50) NOT NULL,
                                                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                created_by CHAR(36) NOT NULL,
                                                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                updated_by CHAR(36) NOT NULL,
                                                deleted_at DATETIME NULL,
                                                deleted_by CHAR(36) NULL,
                                                PRIMARY KEY (id),
                                                UNIQUE KEY uk_consultation_renewal_interests_detail_type (consultation_renewal_detail_id, interest_type),
                                                CONSTRAINT chk_consultation_renewal_interests_type CHECK (interest_type IN ('PREMIUM', 'COVERAGE', 'MATURITY', 'REFUND', 'ALTERNATIVE_PRODUCT')),
                                                CONSTRAINT fk_consultation_renewal_interests_detail FOREIGN KEY (consultation_renewal_detail_id) REFERENCES consultation_renewal_details(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_claim_details (
                                            id CHAR(36) NOT NULL,
                                            consultation_id CHAR(36) NOT NULL,
                                            claim_stage VARCHAR(30) NOT NULL,
                                            claim_event_date DATE NULL,
                                            claim_reason_detail VARCHAR(500) NULL,
                                            hospital_name VARCHAR(100) NULL,
                                            diagnosis_or_treatment VARCHAR(500) NULL,
                                            hospitalization_status VARCHAR(30) NULL,
                                            surgery_status VARCHAR(30) NULL,
                                            claim_result VARCHAR(30) NOT NULL,
                                            guidance_summary VARCHAR(500) NULL,
                                            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            created_by CHAR(36) NOT NULL,
                                            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                            updated_by CHAR(36) NOT NULL,
                                            deleted_at DATETIME NULL,
                                            deleted_by CHAR(36) NULL,
                                            PRIMARY KEY (id),
                                            UNIQUE KEY uk_consultation_claim_details_consultation (consultation_id),
                                            CONSTRAINT fk_consultation_claim_details_consultation FOREIGN KEY (consultation_id) REFERENCES consultations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_claim_types (
                                          id CHAR(36) NOT NULL,
                                          consultation_claim_detail_id CHAR(36) NOT NULL,
                                          claim_type VARCHAR(50) NOT NULL,
                                          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          created_by CHAR(36) NOT NULL,
                                          updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                          updated_by CHAR(36) NOT NULL,
                                          deleted_at DATETIME NULL,
                                          deleted_by CHAR(36) NULL,
                                          PRIMARY KEY (id),
                                          UNIQUE KEY uk_consultation_claim_types_detail_type (consultation_claim_detail_id, claim_type),
                                          CONSTRAINT chk_consultation_claim_types_type CHECK (claim_type IN ('ACTUAL_MEDICAL', 'HOSPITALIZATION', 'OUTPATIENT', 'SURGERY', 'DIAGNOSIS', 'INJURY', 'FRACTURE', 'BURN', 'DEATH', 'DISABILITY', 'OTHER')),
                                          CONSTRAINT fk_consultation_claim_types_detail FOREIGN KEY (consultation_claim_detail_id) REFERENCES consultation_claim_details(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_claim_review_items (
                                                 id CHAR(36) NOT NULL,
                                                 consultation_claim_detail_id CHAR(36) NOT NULL,
                                                 review_type VARCHAR(50) NOT NULL,
                                                 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                 created_by CHAR(36) NOT NULL,
                                                 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                 updated_by CHAR(36) NOT NULL,
                                                 deleted_at DATETIME NULL,
                                                 deleted_by CHAR(36) NULL,
                                                 PRIMARY KEY (id),
                                                 UNIQUE KEY uk_consultation_claim_review_items_detail_type (consultation_claim_detail_id, review_type),
                                                 CONSTRAINT chk_consultation_claim_review_items_type CHECK (review_type IN ('COVERAGE_ELIGIBLE', 'EXEMPTION_PERIOD', 'EXCLUSION_POSSIBILITY', 'PREVIOUS_CLAIM_HISTORY')),
                                                 CONSTRAINT fk_consultation_claim_review_items_detail FOREIGN KEY (consultation_claim_detail_id) REFERENCES consultation_claim_details(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_drafts (
                                     id CHAR(36) NOT NULL,
                                     customer_id CHAR(36) NULL,
                                     fp_id CHAR(36) NOT NULL,
                                     contract_id CHAR(36) NULL,
                                     consultation_type VARCHAR(30) NOT NULL,
                                     consultation_channel VARCHAR(30) NOT NULL,
                                     consulted_at DATETIME NOT NULL,
                                     special_note TEXT NULL,
                                     next_scheduled_at DATETIME NULL,
                                     draft_data JSON NOT NULL,
                                     last_saved_at DATETIME NOT NULL,
                                     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     created_by CHAR(36) NOT NULL,
                                     updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                     updated_by CHAR(36) NOT NULL,
                                     deleted_at DATETIME NULL,
                                     deleted_by CHAR(36) NULL,
                                     PRIMARY KEY (id),
                                     CONSTRAINT chk_consultation_drafts_type CHECK (consultation_type IN ('NEW_CONTRACT', 'CLAIM', 'TERMINATION', 'RENEWAL')),
                                     CONSTRAINT chk_consultation_drafts_channel CHECK (consultation_channel IN ('VISIT', 'PHONE', 'MESSAGE')),
                                     CONSTRAINT fk_consultation_drafts_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
                                     CONSTRAINT fk_consultation_drafts_fp FOREIGN KEY (fp_id) REFERENCES users(id),
                                     CONSTRAINT fk_consultation_drafts_contract FOREIGN KEY (contract_id) REFERENCES contracts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE consultation_ai_briefings (
                                           id CHAR(36) NOT NULL,
                                           update_sequence INT NOT NULL,
                                           customer_id CHAR(36) NOT NULL,
                                           briefing_content TEXT NOT NULL,
                                           created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           created_by CHAR(36) NOT NULL,
                                           updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                           updated_by CHAR(36) NOT NULL,
                                           deleted_at DATETIME NULL,
                                           deleted_by CHAR(36) NULL,
                                           PRIMARY KEY (id),
                                           UNIQUE KEY uk_consultation_ai_briefings_customer_sequence (customer_id, update_sequence),
                                           CONSTRAINT fk_consultation_ai_briefings_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE gross_commission_records (
                                          id CHAR(36) NOT NULL,
                                          commission_month VARCHAR(7) NOT NULL,
                                          contract_id CHAR(36) NOT NULL,
                                          insurance_company_id CHAR(36) NOT NULL,
                                          insurance_product_id CHAR(36) NOT NULL,
                                          commission_type VARCHAR(30) NOT NULL,
                                          gross_commission_amount DECIMAL(15,2) NOT NULL,
                                          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          created_by CHAR(36) NOT NULL,
                                          PRIMARY KEY (id),
                                          CONSTRAINT chk_gross_commission_records_month CHECK (commission_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_gross_commission_records_type CHECK (commission_type IN ('INITIAL', 'MAINTENANCE', 'RECOVERY')),
    CONSTRAINT fk_gross_commission_records_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_gross_commission_records_company FOREIGN KEY (insurance_company_id) REFERENCES insurance_companies(id),
    CONSTRAINT fk_gross_commission_records_product FOREIGN KEY (insurance_product_id) REFERENCES insurance_products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE payment_commission_records (
                                            id CHAR(36) NOT NULL,
                                            commission_month VARCHAR(7) NOT NULL,
                                            gross_commission_id CHAR(36) NOT NULL,
                                            contract_id CHAR(36) NOT NULL,
                                            fp_id CHAR(36) NOT NULL,
                                            organization_id CHAR(36) NOT NULL,
                                            insurance_company_id CHAR(36) NOT NULL,
                                            insurance_product_id CHAR(36) NOT NULL,
                                            commission_type VARCHAR(30) NOT NULL,
                                            base_commission_amount DECIMAL(15,2) NOT NULL,
                                            fp_payment_rate DECIMAL(5,2) NOT NULL,
                                            commission_amount DECIMAL(15,2) NOT NULL,
                                            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            created_by CHAR(36) NOT NULL,
                                            PRIMARY KEY (id),
                                            CONSTRAINT chk_payment_commission_records_month CHECK (commission_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT chk_payment_commission_records_type CHECK (commission_type IN ('INITIAL_PAYMENT', 'MAINTENANCE_PAYMENT', 'RECOVERY_COLLECTION')),
    CONSTRAINT fk_payment_commission_records_gross FOREIGN KEY (gross_commission_id) REFERENCES gross_commission_records(id),
    CONSTRAINT fk_payment_commission_records_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_payment_commission_records_fp FOREIGN KEY (fp_id) REFERENCES users(id),
    CONSTRAINT fk_payment_commission_records_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_payment_commission_records_company FOREIGN KEY (insurance_company_id) REFERENCES insurance_companies(id),
    CONSTRAINT fk_payment_commission_records_product FOREIGN KEY (insurance_product_id) REFERENCES insurance_products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE fp_commission_monthly_closing (
                                               id CHAR(36) NOT NULL,
                                               closing_month VARCHAR(7) NOT NULL,
                                               fp_id CHAR(36) NOT NULL,
                                               organization_id CHAR(36) NOT NULL,
                                               total_initial_payment_amount DECIMAL(15,2) NOT NULL,
                                               total_maintenance_payment_amount DECIMAL(15,2) NOT NULL,
                                               total_recovery_collection_amount DECIMAL(15,2) NOT NULL,
                                               total_payment_amount DECIMAL(15,2) NOT NULL,
                                               net_commission_amount DECIMAL(15,2) NOT NULL,
                                               contract_count INT NOT NULL,
                                               recovery_contract_count INT NOT NULL,
                                               closed_at DATETIME NOT NULL,
                                               PRIMARY KEY (id),
                                               UNIQUE KEY uk_fp_commission_monthly_closing_month_fp (closing_month, fp_id),
                                               CONSTRAINT chk_fp_commission_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_fp_commission_monthly_closing_fp FOREIGN KEY (fp_id) REFERENCES users(id),
    CONSTRAINT fk_fp_commission_monthly_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE branch_commission_monthly_closing (
                                                   id CHAR(36) NOT NULL,
                                                   closing_month VARCHAR(7) NOT NULL,
                                                   organization_id CHAR(36) NOT NULL,
                                                   total_initial_payment_amount DECIMAL(15,2) NOT NULL,
                                                   total_maintenance_payment_amount DECIMAL(15,2) NOT NULL,
                                                   total_recovery_collection_amount DECIMAL(15,2) NOT NULL,
                                                   total_payment_amount DECIMAL(15,2) NOT NULL,
                                                   net_commission_amount DECIMAL(15,2) NOT NULL,
                                                   fp_count INT NOT NULL,
                                                   contract_count INT NOT NULL,
                                                   recovery_contract_count INT NOT NULL,
                                                   closed_at DATETIME NOT NULL,
                                                   PRIMARY KEY (id),
                                                   UNIQUE KEY uk_branch_commission_monthly_closing_month_org (closing_month, organization_id),
                                                   CONSTRAINT chk_branch_commission_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_branch_commission_monthly_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE income_commission_monthly_closing (
                                                   id CHAR(36) NOT NULL,
                                                   closing_month VARCHAR(7) NOT NULL,
                                                   net_income_commission_amount DECIMAL(15,2) NOT NULL,
                                                   total_initial_gross_commission_amount DECIMAL(15,2) NOT NULL,
                                                   total_maintenance_gross_commission_amount DECIMAL(15,2) NOT NULL,
                                                   total_payment_commission_amount DECIMAL(15,2) NOT NULL,
                                                   total_insurance_recovery_amount DECIMAL(15,2) NOT NULL,
                                                   total_fp_recovery_collection_amount DECIMAL(15,2) NOT NULL,
                                                   closed_at DATETIME NOT NULL,
                                                   PRIMARY KEY (id),
                                                   UNIQUE KEY uk_income_commission_monthly_closing_month (closing_month),
                                                   CONSTRAINT chk_income_commission_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$')
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE branch_income_commission_monthly_closing (
                                                          id CHAR(36) NOT NULL,
                                                          closing_month VARCHAR(7) NOT NULL,
                                                          organization_id CHAR(36) NOT NULL,
                                                          net_income_commission_amount DECIMAL(15,2) NOT NULL,
                                                          total_initial_gross_commission_amount DECIMAL(15,2) NOT NULL,
                                                          total_maintenance_gross_commission_amount DECIMAL(15,2) NOT NULL,
                                                          total_gross_commission_amount DECIMAL(15,2) NOT NULL,
                                                          total_payment_commission_amount DECIMAL(15,2) NOT NULL,
                                                          total_insurance_recovery_amount DECIMAL(15,2) NOT NULL,
                                                          total_fp_recovery_collection_amount DECIMAL(15,2) NOT NULL,
                                                          contract_count INT NOT NULL,
                                                          fp_count INT NOT NULL,
                                                          closed_at DATETIME NOT NULL,
                                                          PRIMARY KEY (id),
                                                          UNIQUE KEY uk_branch_income_commission_monthly_closing_month_org (closing_month, organization_id),
                                                          CONSTRAINT chk_branch_income_commission_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_branch_income_commission_monthly_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE handover_requests (
                                   id CHAR(36) NOT NULL,
                                   customer_id CHAR(36) NOT NULL,
                                   current_fp_id CHAR(36) NULL,
                                   request_type VARCHAR(30) NOT NULL,
                                   request_status VARCHAR(30) NOT NULL,
                                   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   created_by CHAR(36) NOT NULL,
                                   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                   updated_by CHAR(36) NOT NULL,
                                   deleted_at DATETIME NULL,
                                   deleted_by CHAR(36) NULL,
                                   PRIMARY KEY (id),
                                   CONSTRAINT chk_handover_requests_status CHECK (request_status IN ('MANAGER_PENDING', 'COMPLETED')),
                                   CONSTRAINT fk_handover_requests_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
                                   CONSTRAINT fk_handover_requests_current_fp FOREIGN KEY (current_fp_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE handover_recommendations (
                                          id CHAR(36) NOT NULL,
                                          handover_request_id CHAR(36) NOT NULL,
                                          recommended_fp_id CHAR(36) NOT NULL,
                                          recommended_fp_name VARCHAR(50) NOT NULL,
                                          recommendation_reason TEXT NULL,
                                          approval_status VARCHAR(30) NOT NULL,
                                          reviewed_by CHAR(36) NULL,
                                          approved_at DATETIME NULL,
                                          rejected_at DATETIME NULL,
                                          rejection_reason VARCHAR(255) NULL,
                                          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          PRIMARY KEY (id),
                                          CONSTRAINT chk_handover_recommendations_approval_status CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED')),
                                          CONSTRAINT fk_handover_recommendations_request FOREIGN KEY (handover_request_id) REFERENCES handover_requests(id),
                                          CONSTRAINT fk_handover_recommendations_recommended_fp FOREIGN KEY (recommended_fp_id) REFERENCES users(id),
                                          CONSTRAINT fk_handover_recommendations_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE customer_fp_history (
                                     id CHAR(36) NOT NULL,
                                     customer_fp_sequence INT NOT NULL,
                                     customer_id CHAR(36) NOT NULL,
                                     handover_request_id CHAR(36) NOT NULL,
                                     before_fp_id CHAR(36) NOT NULL,
                                     before_fp_name VARCHAR(50) NOT NULL,
                                     after_fp_id CHAR(36) NOT NULL,
                                     after_fp_name VARCHAR(50) NOT NULL,
                                     changed_reason VARCHAR(255) NOT NULL,
                                     changed_at DATETIME NOT NULL,
                                     changed_by CHAR(36) NOT NULL,
                                     PRIMARY KEY (id),
                                     CONSTRAINT fk_customer_fp_history_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
                                     CONSTRAINT fk_customer_fp_history_handover_request FOREIGN KEY (handover_request_id) REFERENCES handover_requests(id),
                                     CONSTRAINT fk_customer_fp_history_before_fp FOREIGN KEY (before_fp_id) REFERENCES users(id),
                                     CONSTRAINT fk_customer_fp_history_after_fp FOREIGN KEY (after_fp_id) REFERENCES users(id),
                                     CONSTRAINT fk_customer_fp_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE fp_monthly_performance_closing (
                                                id CHAR(36) NOT NULL,
                                                closing_month VARCHAR(7) NOT NULL,
                                                fp_id CHAR(36) NOT NULL,
                                                organization_id CHAR(36) NOT NULL,
                                                new_contract_count INT NOT NULL,
                                                completed_contract_count INT NOT NULL,
                                                retention_rate DECIMAL(5,2) NOT NULL,
                                                consultation_count INT NOT NULL,
                                                customer_count INT NOT NULL,
                                                new_handover_customer_count INT NOT NULL,
                                                commission_amount DECIMAL(15,2) NOT NULL,
                                                performance_score DECIMAL(10,2) NOT NULL,
                                                branch_rank INT NOT NULL,
                                                total_rank INT NOT NULL,
                                                closed_at DATETIME NOT NULL,
                                                PRIMARY KEY (id),
                                                UNIQUE KEY uk_fp_monthly_performance_closing_month_fp (closing_month, fp_id),
                                                CONSTRAINT chk_fp_monthly_performance_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_fp_monthly_performance_closing_fp FOREIGN KEY (fp_id) REFERENCES users(id),
    CONSTRAINT fk_fp_monthly_performance_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE branch_contract_monthly_closing (
                                                 id CHAR(36) NOT NULL,
                                                 closing_month VARCHAR(7) NOT NULL,
                                                 organization_id CHAR(36) NOT NULL,
                                                 insurance_company_id CHAR(36) NULL,
                                                 insurance_category_id CHAR(36) NULL,
                                                 total_contract_count INT NOT NULL,
                                                 active_contract_count INT NOT NULL,
                                                 completed_contract_count INT NOT NULL,
                                                 terminated_contract_count INT NOT NULL,
                                                 contract_success_rate DECIMAL(5,2) NOT NULL,
                                                 retention_rate DECIMAL(5,2) NOT NULL,
                                                 total_monthly_premium_amount DECIMAL(15,2) NOT NULL,
                                                 closed_at DATETIME NOT NULL,
                                                 PRIMARY KEY (id),
                                                 UNIQUE KEY uk_branch_contract_monthly_closing_scope (closing_month, organization_id, insurance_company_id, insurance_category_id),
                                                 CONSTRAINT chk_branch_contract_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_branch_contract_monthly_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_branch_contract_monthly_closing_company FOREIGN KEY (insurance_company_id) REFERENCES insurance_companies(id),
    CONSTRAINT fk_branch_contract_monthly_closing_category FOREIGN KEY (insurance_category_id) REFERENCES insurance_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE all_branch_contract_monthly_closing (
                                                     id CHAR(36) NOT NULL,
                                                     closing_month VARCHAR(7) NOT NULL,
                                                     insurance_company_id CHAR(36) NULL,
                                                     insurance_category_id CHAR(36) NULL,
                                                     total_contract_count INT NOT NULL,
                                                     active_contract_count INT NOT NULL,
                                                     completed_contract_count INT NOT NULL,
                                                     terminated_contract_count INT NOT NULL,
                                                     contract_success_rate DECIMAL(5,2) NOT NULL,
                                                     retention_rate DECIMAL(5,2) NOT NULL,
                                                     total_monthly_premium_amount DECIMAL(15,2) NOT NULL,
                                                     closed_at DATETIME NOT NULL,
                                                     PRIMARY KEY (id),
                                                     UNIQUE KEY uk_all_branch_contract_monthly_closing_scope (closing_month, insurance_company_id, insurance_category_id),
                                                     CONSTRAINT chk_all_branch_contract_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_all_branch_contract_monthly_closing_company FOREIGN KEY (insurance_company_id) REFERENCES insurance_companies(id),
    CONSTRAINT fk_all_branch_contract_monthly_closing_category FOREIGN KEY (insurance_category_id) REFERENCES insurance_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE branch_customer_monthly_closing (
                                                 id CHAR(36) NOT NULL,
                                                 closing_month VARCHAR(7) NOT NULL,
                                                 organization_id CHAR(36) NOT NULL,
                                                 fp_count INT NOT NULL,
                                                 customer_count INT NOT NULL,
                                                 long_term_unmanaged_customer_count INT NOT NULL,
                                                 closed_at DATETIME NOT NULL,
                                                 PRIMARY KEY (id),
                                                 UNIQUE KEY uk_branch_customer_monthly_closing_month_org (closing_month, organization_id),
                                                 CONSTRAINT chk_branch_customer_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_branch_customer_monthly_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE all_branch_customer_monthly_closing (
                                                     id CHAR(36) NOT NULL,
                                                     closing_month VARCHAR(7) NOT NULL,
                                                     fp_count INT NOT NULL,
                                                     customer_count INT NOT NULL,
                                                     long_term_unmanaged_customer_count INT NOT NULL,
                                                     closed_at DATETIME NOT NULL,
                                                     PRIMARY KEY (id),
                                                     UNIQUE KEY uk_all_branch_customer_monthly_closing_month (closing_month),
                                                     CONSTRAINT chk_all_branch_customer_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$')
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE branch_handover_monthly_closing (
                                                 id CHAR(36) NOT NULL,
                                                 closing_month VARCHAR(7) NOT NULL,
                                                 organization_id CHAR(36) NOT NULL,
                                                 requested_count INT NOT NULL,
                                                 recommended_count INT NOT NULL,
                                                 manager_pending_count INT NOT NULL,
                                                 approved_count INT NOT NULL,
                                                 rejected_count INT NOT NULL,
                                                 completed_count INT NOT NULL,
                                                 canceled_count INT NOT NULL,
                                                 closed_at DATETIME NOT NULL,
                                                 PRIMARY KEY (id),
                                                 UNIQUE KEY uk_branch_handover_monthly_closing_month_org (closing_month, organization_id),
                                                 CONSTRAINT chk_branch_handover_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT fk_branch_handover_monthly_closing_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE all_branch_handover_monthly_closing (
                                                     id CHAR(36) NOT NULL,
                                                     closing_month VARCHAR(7) NOT NULL,
                                                     requested_count INT NOT NULL,
                                                     recommended_count INT NOT NULL,
                                                     manager_pending_count INT NOT NULL,
                                                     approved_count INT NOT NULL,
                                                     rejected_count INT NOT NULL,
                                                     completed_count INT NOT NULL,
                                                     canceled_count INT NOT NULL,
                                                     closed_at DATETIME NOT NULL,
                                                     PRIMARY KEY (id),
                                                     UNIQUE KEY uk_all_branch_handover_monthly_closing_month (closing_month),
                                                     CONSTRAINT chk_all_branch_handover_monthly_closing_month CHECK (closing_month REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$')
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE notifications (
                               id CHAR(36) NOT NULL,
                               receiver_id CHAR(36) NOT NULL,
                               notification_type VARCHAR(30) NOT NULL,
                               title VARCHAR(100) NOT NULL,
                               content VARCHAR(500) NOT NULL,
                               target_type VARCHAR(30) NULL,
                               target_id CHAR(36) NULL,
                               read_yn BOOLEAN NOT NULL,
                               read_at DATETIME NULL,
                               created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               deleted_at DATETIME NULL,
                               PRIMARY KEY (id),
                               CONSTRAINT fk_notifications_receiver FOREIGN KEY (receiver_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
